Algoritmo "VisuAlgExercicio5.6.1A"
// 
//  
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Gustavo Mandu Ferreira Matori
// Data atual  : 25/04/2025
Var
// Seção de Declarações das variáveis 
   numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para numero de 15 ate 200 faça
        escreval("Quadrado de: ", numero, " é: ", numero * numero)
   
   
   fimpara

Fimalgoritmo