Algoritmo "enquanto"
//
//
// Descrição   : Mostra o enquanto funcionando
// Autor(a)    : Gustavo Mandu Ferreira Matori
// Data atual  : 24/03/2025
Var
   // Seção de Declarações das variáveis
   contadora: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   
   enquanto contadora < 10 faca
      escreval("Somente a dor coletiva gera união ",contadora)
      contadora <- contadora + 1
   fimenquanto
   
Fimalgoritmo